### ISSUE TITLE
BOM links do not work

### ISSUE THREAD

**Issue by mmally** [regnaDkciN/Filament-Scale#1]
First congratulations to this fine scale! I would like to build one of my own, but and try to source the components.
Which is not that easy in Europe.

In the "Filament Scale Instructions.pdf" the Hardware Parts links do not work. Other links in the pdf work fine.
I tested it with two different viewers.
This would save me a lot of work.

**Comment by regnaDkciN** [comment]
I'm glad you liked it.  Thanks for catching the absence of the links.  I don't know why they don't work.  I've attached a text version of the parts list with links to this email.  I'll post a copy of it to the github site.
Good luck with your build.


    On Wednesday, March 16, 2022, 10:00:20 AM EDT, mmally ***@***.***> wrote:  
 
 


First congratulations to this fine scale! I would like to build one of my own, but and try to source the components.
Which is not that easy in Europe.

In the "Filament Scale Instructions.pdf" the Hardware Parts links do not work. Other links in the pdf work fine.
I tested it with two different viewers.
This would save me a lot of work.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
  
Part                                      #   Link
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Adafruit HUZZAH32 – ESP32 Feather         1   https://learn.adafruit.com/adafruit-huzzah32-esp32-feather
Adafruit 1.8” TFT Display                 1   https://www.adafruit.com/product/358
HX711 ADC Converter with 5KG Load Cell    1   https://www.amazon.com/gp/product/B078W2VCP2/ref=as_li_ss_tl?ie=UTF8&linkCode=sl1&tag=replicantfx0d-20&linkId=3d2f04c1e519bb26f0717c80d80ebb15&language=en_US&th=1
DHT22 Temperature and Humidity Sensor     1   https://www.adafruit.com/product/385
Rotary Encoder with Switch Module         1   https://www.microcenter.com/product/618904/inland-ks0013-keystudio-rotary-encoder-module
SPST N.O. Pushbutton Switch (16mm)        1   https://www.amazon.com/gp/product/B07DM2YMT4/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
DPDT Rocker Switch (3/4”)                 1   https://www.radioshack.com/products/dpdt-red-rocker-switch
Resistor, 10K 1/8 Watt                    1
5V Power Supply with Micro USB Connector  1   https://www.microcenter.com/product/510437/micro-connectors-micro-usb-5v-25a-power-adapter-with-on-off-switch-for-raspberry-pi
2-Pin Connector, 0.1”                     1   https://www.allelectronics.com/item/con-242/2-pin-connector-w/header-.10/1.html
3-Pin Connector, 0.1”                     1   https://www.allelectronics.com/item/con-243/3-pin-connector-w/header-0.1/1.html
4-Pin Connector, 0.1”                     3   https://www.allelectronics.com/item/con-244/4-pin-connector-w/header-0.10/1.html
10-Pin Connector, 0.1”                    1   https://www.allelectronics.com/item/con-2410/10-pin-connector-w/header-0.1-spacing/1.html
Hookup Wire
608ZZ Bearing                             4   https://www.amazon.com/gp/product/B00NX1WBA0/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1
Assorted M2 and M3 Screws
M3 Threaded Brass Inserts                15   https://www.amazon.com/gp/product/B07NBTCHP1/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
M3 x 6mm Screw                           15
M3 x 12mm Screw                           6
½” Self-Adhesive Foam Pads                4   https://www.acehardware.com/departments/home-and-decor/cabinet-and-furniture-hardware/protective-furniture-pads/5089586
½” Rubber Grommet                         1   https://www.harborfreight.com/180-piece-harness-grommet-set-67582.html
4” Cable Ties (100 pack)                  5   https://www.harborfreight.com/4-in-white-cable-ties-100-pk-60257.html
3/32” Heat Shrink Tubing                      https://www.harborfreight.com/127-piece-heat-shrink-tubing-set-67524.html
Knob for Rotary Encoder

**Comment by mmally** [comment]
Thank you very much for the BOM.

What is the reason for limiting the spool database to 15?

I have seen that the TFT Display also has a SD Card slot. I am thinking about using this for storing all the filament spool data (currently I have about 50 of them). Adafruit uses this just for  storing pictures, so I am not sure if it is also accessible via SPI and regular libraries. 
I also have an idea to add an RFID reader to automatically identify a spool and update the database automatically.

**Comment by regnaDkciN** [comment]
The main reason that the database is limited to 15 entries is that the menu system can only handle a maximum of 15 items per page.  I suppose you might be able to add multiple pages for the database, or modify the menu code to support more than 15 items.  However, I was a professional programmer for 40 years and I found the ArduinoMenu library extremely difficult to work with.  It uses deeply nested macros and contains only a few comments.  I spent more time trying to get it to do what I needed than I did on the entire rest of the project.
The storage for the database is not a problem.  I think there is enough memory left over in the system to support 50 spools.  However, it would be easy to use the SD card slot for that purpose if you wanted to.  My initial tests with the SD card slot on the TFT display showed that it was pretty easy to use.  You may have noticed on the wiring diagram that the SD card select is wired to the Huzzah even though the software does not use it.  So all you would need to do would be to add the appropriate library and interface to it.
The RFID sounds like a great idea.  I don't think it would be very difficult to add.  Of course there would be some code changes in both the menu subsystem and the main system that would be needed.


    On Thursday, March 17, 2022, 06:17:55 AM EDT, mmally ***@***.***> wrote:  
 


Thank you very much for the BOM.

What is the reason for limiting the spool database to 15?

I have seen that the TFT Display also has a SD Card slot. I am thinking about using this for storing all the filament spool data (currently I have about 50 of them). Adafruit uses this just for storing pictures, so I am not sure if it is also accessible via SPI and regular libraries.
I also have an idea to add an RFID reader to automatically identify a spool and update the database automatically.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mmally** [comment]
Thank you for the valuable input regarding the menu library.
I will first build the scale, add RFID and then think about how to expand the database.

Cheers from Austria

**Comment by regnaDkciN** [comment]
I'm glad I could help.  I hope your build goes well.

    On Thursday, March 17, 2022, 05:44:37 PM EDT, mmally ***@***.***> wrote:  
 
 


Thank you for the valuable input regarding the menu library.
I will first build the scale, add RFID and then think about how to expand the database.

Cheers from Austria

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
